# Configuración principal del proyecto
project:
  name: "Nebura Works" # Nombre del proyecto
  version: "1.0.0" # Versión actual del proyecto
  type: "monorepo" # Indica si el proyecto utiliza un enfoque de monorepo (opcional)
  api-version: "v1" # Versión de la API utilizada
  logs: "config/logs-apps/" # Ruta donde se almacenan los logs de la aplicación
  guildId: ""
  winstonlog: "config/logs-apps/proyect"

# Configuración de entornos
environments:
  default: &default # Configuración por defecto que puede ser heredada por otros entornos
    api:
      port: 3000 # Puerto en el que se ejecutará la API
      host: "localhost" # Dirección del host para la API
      sessions:
        websecret: "dev_secret" # Clave secreta para sesiones web (cambiar en producción)
        jwtsecret: "jwt_secret" # Clave secreta para JWT
      swagger:
        local: "config/api-docs/swagger.yml" # Ruta al archivo de configuración de Swagger
        name: "" # Nombre de la API para la documentación de Swagger
        version: "" # Versión de la API para Swagger
        url: "/api/v1/admin-monitor" # URL base para el monitor de administración
        docs: "/api/v1/api-docs" # URL para acceder a la documentación de la API
        auth:
          name: "luis" # Nombre de usuario para autenticar en Swagger
          password: "luis" # Contraseña para autenticar en Swagger
    database:
      sessions:
        url: "src/structure/database/" # Ruta a la base de datos de sesiones
        name: "sessions" # Nombre de la base de datos de sesiones
    artificial:
      services:
        gemini:
          model: "" # Modelo utilizado por el servicio Gemini (vacío por defecto)
          configsystem: "" # Configuración del sistema para Gemini
          api-key: "" # Clave API para acceder al servicio Gemini
    key-secrets:
      administrator: "" # Clave secreta para el administrador
      customer: "" # Clave secreta para el cliente

  production: # Configuración específica para el entorno de producción
    <<: *default # Hereda la configuración por defecto
    api:
      port: 3000 # Puerto en el que se ejecutará la API en producción
      host: "" # Dirección del host para producción (debe configurarse)
      sessions:
        websecret: "prod_secret" # Clave secreta para sesiones web en producción

# Configuración de módulos
modules:
  discord: # Configuración del módulo de Discord
    token: "MTM1NjY0ODI0MDM2MzIxMzAxMQ.GpaulA.Hz4-1XALlpmVnK_lhMYkD-LMGa83eIPuDE73Y8" # Token del bot de Discord
    clientId: "1356648240363213011" # ID del cliente de Discord
    clientSecret: ""
    owners: # Lista de IDs de usuarios que son propietarios del bot
      - "" # ID del propietario del bot
      - ""
    prefix: "!" # Prefijo para los comandos del bot
    presence: # Configuración de presencia del bot
      status: "online" # Estado del bot (opciones: online, idle, dnd, invisible)
      activity:
        type: "WATCHING" # Tipo de actividad (opciones: PLAYING, WATCHING, LISTENING, STREAMING)
        name: "Nebura Works" # Nombre de la actividad que se muestra
        url: "" # URL asociada a la actividad (opcional)
    configs: # Configuración de rutas para el módulo de Discord
      eventpath: "src/modules/discord/bot/events/" # Ruta a los eventos del bot
      commandpath: "src/modules/discord/bot/commands/slash/" # Ruta a los comandos del bot
      componentspath: "src/modules/discord/bot/interactions" # Ruta a los componentes del bot
      addonspath: "src/modules/discord/addons/" # Ruta a los complementos del bot
      precommands: "src/modules/discord/bot/commands/message/" # Ruta a los precomandos del bot
      bot-extensions:
        - ".js" # Extensiones de archivo soportadas para el bot
        - ".ts" # Extensiones de archivo soportadas para el bot
  whatsapp: # Configuración del módulo de WhatsApp
    enabled: false # Indica si el módulo de WhatsApp está habilitado

# Configuración de moderación
moderation:
  notifications:
    urlapi: "https://discord.com/api" # URL base de la API de Discord
    version: "v10" # Versión de la API de Discord
    webhooks: # Configuración de webhooks para notificaciones
      token: "" # Token del webhook
      id: "" # ID del webhook
      avatarURL: "" # URL del avatar para el webhook (opcional)
