# =============================================================================
# Example configuration file for Nebura Works
# Fill in the values according to your environment before using in production.
# =============================================================================

# ---------------------------------------------------------------------------
# PROJECT SETTINGS
# ---------------------------------------------------------------------------
project:
  name: ""                # Project name (string)
  version: ""             # Project version (string, e.g., "1.0.0")
  type: ""                # Project type, e.g., "monorepo" (string, optional)
  api-version: ""         # API version (string, e.g., "v1")
  logs: ""                # Path to store application logs (string)
  winstonlog: ""          # Path for winston logs (string)

# ---------------------------------------------------------------------------
# ENVIRONMENTS
# ---------------------------------------------------------------------------
environments:
  default: &default
    api:
      port:               # API port (number, e.g., 3000)
      host: ""            # API host (string, e.g., "localhost")
      sessions:
        websecret: ""     # Secret key for web sessions (string, change in production)
        jwtsecret: ""     # Secret key for JWT (string)
      swagger:
        local: ""         # Path to Swagger config file (string)
        name: ""          # API name for Swagger (string)
        version: ""       # API version for Swagger (string)
        url: ""           # Base URL for admin monitor (string)
        docs: ""          # URL for API documentation (string)
        auth:
          name: ""        # Username for Swagger authentication (string)
          password: ""    # Password for Swagger authentication (string)
    database:
      sessions:
        url: ""           # Path to sessions database (string)
        name: ""          # Sessions database name (string)
    artificial:
      services:
        gemini:
          model: ""        # Gemini service model (string)
          configsystem: "" # Gemini system config (string)
          api-key: ""      # API key for Gemini service (string)
    key-secrets:
      administrator: ""   # Secret key for administrator (string)
      customer: ""        # Secret key for customer (string)

  production:
    <<: *default
    api:
      port:               # API port for production (number)
      host: ""            # Host for production (string)
      sessions:
        websecret: ""     # Secret key for web sessions in production (string)

# ---------------------------------------------------------------------------
# MODULES
# ---------------------------------------------------------------------------
modules:
  discord:
    token: ""             # Discord bot token (string)
    clientId: ""          # Discord client ID (string)
    clientSecret: ""      # Discord client secret (string)
    guildId: ""           # Discord server ID (string)
    owners:               # List of bot owner user IDs (array of strings)
      - ""
    prefix: ""            # Bot command prefix (string)
    presence:
      status: ""          # Bot status (e.g., "online", "idle", "dnd", "invisible")
      activity:
        type: ""          # Activity type (e.g., "PLAYING", "WATCHING")
        name: ""          # Activity name (string)
        url: ""           # Activity URL (string, optional)
    configs:
      eventpath: ""       # Path to bot events (string)
      commandpath: ""     # Path to slash commands (string)
      componentspath: ""  # Path to components/interactions (string)
      addonspath: ""      # Path to addons (string)
      precommands: ""     # Path to precommands (string)
      bot-extensions:     # Supported bot file extensions (array of strings)
        - ""
  whatsapp:
    enabled: false        # Whether WhatsApp module is enabled (boolean)

# ---------------------------------------------------------------------------
# MODERATION
# ---------------------------------------------------------------------------
moderation:
  notifications:
    urlapi: ""            # Base URL for Discord API (string)
    version: ""           # Discord API version (string)
    webhooks:
      token: ""           # Webhook token (string)
      id: ""              # Webhook ID (string)
      avatarURL: ""       # Webhook avatar URL (string, optional)

# ---------------------------------------------------------------------------
# TASKS
# ---------------------------------------------------------------------------
tasks:
  reloadproyect:
    enabled: false        # Enable/disable automatic project reload (boolean)
    cron: ""              # Cron expression for reload (string, e.g., "0 0 * * *")
    cmd: ""               # Command to execute reload (string)
    cmdreload: ""         # Specific command for reload (string)
