# ./config.yml (en la raíz del proyecto)
project:
  name: "Nebura Works"  # Ejemplo: Nombre del proyecto
  version: "1.0.0"
  type: "monorepo"  # Opcional: Si usas workspaces
  api-version: "v1"  # Versión de la API

environments:
  default: &default
    api:
      port: 3000
      host: "localhost"
      sessions:
        websecret: "dev_secret"  # Cambia esto en producción
        jwtsecret: "jwt_secret"
      swagger:
        local: "docs/swagger.yml"  # Ruta al archivo swagger.yml
        name: ""
        version: "" 
        url: "/api/v1/admin-monitor"
        docs: "/api/v1/api-docs"  # URL para acceder a la documentación
        auth:
          name: "luis"
          password: "luis"
    database:
      sessions:
        url: "./src/infrastructure/database/"
        name: "sessions"
    artificial:
      services:
        gemini:
          model: ""
          configsystem: "" 
          api-key: ""
    key-secrets:
      administrator: ""
      customer: ""


  production:
    <<: *default  # Hereda configs de 'default'
    api:
      port: 3000
      host: "" 
      sessions:
        websecret: "prod_secret"